'''
Alabama = StateIncomeTax("ALABAMA", "AL", 0.0367)
Arizona = StateIncomeTax("ARIZONA", "AZ", 0.0515)
Arkansas = StateIncomeTax("ARKANSAS", "AR", 0.0397)
California = StateIncomeTax("CALIFORNIA", "CA", 0.09)
Connecticut = StateIncomeTax("CONNECTICUT", "CT", 0.0479)
Delaware = StateIncomeTax("DELAWARE", "DE", 0.0389)
Georgia = StateIncomeTax("GEORGIA", "GA", 0.287)
Hawaii = StateIncomeTax("HAWAII", "HI", 0.078)
Idaho = StateIncomeTax("IDAHO", "ID", 0.314)
Iowa = StateIncomeTax("IOWA", "IA", 0.0578)
Kansas = StateIncomeTax("KANSAS", "KS", 0.0451)
Louisiana = StateIncomeTax("LOUISIANA", "LA", 0.04)
Maine = StateIncomeTax("MAINE", "ME", 0.06)
Maryland = StateIncomeTax("MARYLAND", "MD", 0.0413)
Minnesota = StateIncomeTax("MINNESOTA", "MN", 0.0763)
Mississippi = StateIncomeTax("MISSISSIPPI", "MS", 0.04)
Missouri = StateIncomeTax("MISSOURI", "MO", 0.0387)
Montana = StateIncomeTax("MONTANA", "MT", 0.043)
Nebraska = StateIncomeTax("NEBRASKA", "NE", 0.0531)
New_Jersey = StateIncomeTax("NEW JERSEY", "NJ", 0.0735)
New_Mexico = StateIncomeTax("NEW MEXICO", "NM", 0.0378)
New_York = StateIncomeTax("NEW YORK", "NY", 0.0631)
North_Dakota = StateIncomeTax("NORTH DAKOTA", "ND", 0.0189)
Ohio = StateIncomeTax("OHIO", "OH", 0.0283)
Oklahoma = StateIncomeTax("OKLAHOMA", "OK", 0.05)
Oregon = StateIncomeTax("OREGON", "OR", 0.079)
Rhode_Island = StateIncomeTax("RHODE ISLAND", "RI", 0.453)
South_Carolina = StateIncomeTax("SOUTH CAROLINA", "SC", 0.07)
Vermont = StateIncomeTax("VERMONT", "VT", 0.0532)
Virginia = StateIncomeTax("VIRGINIA", "VA", 0.0575)
West_Virginia = StateIncomeTax("WEST VIRGINIA", "WV", 0.0585)
Wisconsin = StateIncomeTax("WISCONSIN", "WI", 0.0585)
'''
def Calculate_alabama(income):

